services:
  - type: web
    name: leafit-backend
    runtime: python
    buildCommand: pip install -r requirements.txt && cd backend && python manage.py collectstatic --noinput
    startCommand: cd backend && gunicorn config.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: DEBUG
        value: False
